config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {
    # :sessions => "employee/sessions",
    :registrations => "employees/registrations"
  }

  devise_for :admins, :path => '', :path_names => {:sign_up => "s9442161" }

  root 'home#index'
  get 'home/about'

  resources :home, only: [:show, :edit, :update, :destroy]
  resources :qualifications, only: [:edit, :update]
  resources :leaves, only: [:edit, :update]
  resources :salaries, only: [:edit, :update]

  get 'apply/apply_leave'
  # put 'apply/:id', to: 'apply#update'
  put 'apply/update'

  get 'approve/dashboard'
  put 'approve/update'
  get 'status/leave_status'
  put 'status/update'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @employees = Employee.all
    if employee_signed_in?
      @one_employee = Employee.find(current_employee.id)
      @total_leave = @one_employee.leave.sick.to_i + @one_employee.leave.privileged.to_i + @one_employee.leave.breavement.to_i + @one_employee.leave.study_leave.to_i + @one_employee.leave.time_off.to_i + @one_employee.leave.maternity.to_i + @one_employee.leave.paternity.to_i + @one_employee.leave.optional.to_i
      @total_salary = @one_employee.salary.basic_pay.to_i + @one_employee.salary.hra.to_i + @one_employee.salary.statutory_bonus.to_i + @one_employee.salary.special_allowance.to_i
    end
  end

  def about
  end

  def show
    if admin_signed_in?
    @employee = Employee.find(params[:id])
    @total_leave = @employee.leave.sick.to_i + @employee.leave.privileged.to_i + @employee.leave.breavement.to_i + @employee.leave.study_leave.to_i + @employee.leave.time_off.to_i + @employee.leave.maternity.to_i + @employee.leave.paternity.to_i + @employee.leave.optional.to_i
    @total_salary = @employee.salary.basic_pay.to_i + @employee.salary.hra.to_i + @employee.salary.statutory_bonus.to_i + @employee.salary.special_allowance.to_i
    else
      redirect_to admin_session_path
    end
  end

  def edit
    if admin_signed_in?
      @employee = Employee.find(params[:id])
    else
      redirect_to admin_session_path
    end
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      flash[:notice] = "Employee details was updated successfully"
      redirect_to home_path(@employee.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to root_path
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :dob, :phone_number, :gender, :martial_status, :blood_group, :fathers_name, :mothers_name, :address)
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_employee.html.erb
<div class="container py-5 h-50">
  <div class="row d-flex justify-content-center align-items-center h-100 ">
    <div>
      <div class="card bg-dark text-white" style="border-radius: 1rem;">
        <div class="card-body p-5 text-center" >
          <h2 class="fw-bold mb-2 text-uppercase">Employees</h2>
          <div class="mb-md-5 mt-md-4 pb-5">

            <table  class="text-light table table-dark table-hover table-bordered table-responsive table-striped">
              <thead>
              <tr>
                <th>Name</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th colspan="3">Actions</th>
              </tr>
              </thead>

              <tbody >
              <% @employees.each do |employee| %>
                <tr>
                  <td><%= employee.name %> </td>
                  <td> <%= employee.phone_number %> </td>
                  <td> <%= employee.email %> </td>
                  <td> <%= link_to 'View', home_path(employee.id), class:"btn btn-success"%> </td>
                  <td> <%= link_to 'Edit', edit_home_path(employee.id), class:"btn btn-info"%> </td>
                  <td> <%= button_to 'Delete',home_path(employee.id),data: { confirm: "This will delete the Employee. Are you sure?" }, method: :delete, class:"btn btn-danger" %> </td>
                </tr>
              <% end %>
              </tbody>
            </table>
            <br>
            <%= link_to 'Add new Employee', new_employee_registration_path, class:"btn btn-primary" %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>









<!--<table  class="text-light table">-->
<!--  <thead>-->
<!--  <tr>-->
<!--    <th>Name</th>-->
<!--    <th>Phone Number</th>-->
<!--    <th>Email</th>-->
<!--    <th colspan="3">Actions</th>-->
<!--  </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
  <%# @employees.each do |employee| %>
<!--    <tr>-->
<!--      <td><%#= employee.name %> </td>-->
<!--      <td> <%#= employee.phone_number %> </td>-->
<!--      <td> <%#= employee.email %> </td>-->
<!--      <td> <%#= link_to 'Show', home_path(employee.id)%> </td>-->
<!--      <td> <%#= link_to 'Edit', edit_home_path(employee.id)%> </td>-->
<!--      <td> <%#= button_to 'Delete',home_path(employee.id),data: { confirm: "This will delete the Employee. Are you sure?" }, method: :delete %> </td>-->
<!--    </tr>-->
  <%# end %>
<!--  </tbody>-->
<!--</table>-->
<%#= link_to 'Add new Employee', new_employee_registration_path %>

app/views/home/_employee_in.html.erb
<section class="gradient-custom-blue">
  <br>
  <h2 class="fw-bold mb-2 text-uppercase text-md-center"> Welcome <%= @one_employee.name %></h2>
  <div class="container py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-5">

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Basic Details</h3>

            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <table class="table table-borderless table-hover">
                <tbody>
                <tr>
                  <th>Name:</th>
                  <td><%= @one_employee.name %></td>
                </tr>
                <tr>
                  <th>Date of Birth:</th>
                  <td><%= @one_employee.dob %></td>
                </tr>
                <tr>
                  <th>Phone number:</th>
                  <td><%= @one_employee.phone_number %></td>
                </tr>
                <tr>
                  <th>Email:</th>
                  <td><%= @one_employee.email %></td>
                </tr>
                <tr>
                  <th>Gender:</th>
                  <td><%= @one_employee.gender %></td>
                </tr>
                <tr>
                  <th>Martial Status:</th>
                  <td><%= @one_employee.martial_status %></td>
                </tr>
                <tr>
                  <th>Blood Group:</th>
                  <td><%= @one_employee.blood_group %></td>
                </tr>
                <tr>
                  <th>Father's Name:</th>
                  <td><%= @one_employee.fathers_name %></td>
                </tr>
                <tr>
                  <th>Mother's Name:</th>
                  <td><%= @one_employee.mothers_name %></td>
                </tr>
                <tr>
                  <th>Address:</th>
                  <td><%= @one_employee.address %></td>
                </tr>

                </tbody>
              </table>
              <%= link_to 'Edit', edit_employee_registration_path, class:"btn btn-secondary"%>
            </div>
          </div>
        </div>

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Qualification</h3>
            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <table class="table table-borderless table-hover">
                <tbody>
                <tr>
                  <th>Designation:</th>
                  <td><%= @one_employee.qualification.designation %></td>
                </tr>
                <tr>
                  <th>Experience:</th>
                  <td><%= @one_employee.qualification.experience %></td>
                </tr>
                <tr>
                  <th>PG CGPA:</th>
                  <td><%= @one_employee.qualification.pg_cgpa %></td>
                </tr>
                <tr>
                  <th>PG year:</th>
                  <td><%= @one_employee.qualification.pg_year %></td>
                </tr>
                <tr>
                  <th>UG CGPA:</th>
                  <td><%= @one_employee.qualification.ug_cgpa %></td>
                </tr>
                <tr>
                  <th>UG year:</th>
                  <td><%= @one_employee.qualification.ug_year %></td>
                </tr>
                <tr>
                  <th>Diploma CGPA:</th>
                  <td><%= @one_employee.qualification.diploma_cgpa %></td>
                </tr>
                <tr>
                  <th>Diploma year:</th>
                  <td><%= @one_employee.qualification.diploma_year %></td>
                </tr>
                <tr>
                  <th>12th percentage:</th>
                  <td><%= @one_employee.qualification.twelve_th_percent %></td>
                </tr>
                <tr>
                  <th>12th year:</th>
                  <td><%= @one_employee.qualification.twelve_th_year %></td>
                </tr>
                <tr>
                  <th>10th percentage:</th>
                  <td><%= @one_employee.qualification.ten_th_percent %></td>
                </tr>
                <tr>
                  <th>10th year:</th>
                  <td><%= @one_employee.qualification.ten_th_year %></td>
                </tr>

                </tbody>
              </table>
              <%= link_to 'Edit', edit_qualification_path(@one_employee.qualification.id), class:"btn btn-secondary" %>
            </div>
          </div>
        </div>

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Remaining Leaves</h3>
            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <table class="table table-borderless table-hover">
                <tbody>
                <tr>
                  <th>Sick:</th>
                  <td><%= @one_employee.leave.sick %></td>
                </tr>
                <tr>
                  <th>Privileged:</th>
                  <td><%= @one_employee.leave.privileged %></td>
                </tr>
                <tr>
                  <th>Breavement:</th>
                  <td><%= @one_employee.leave.breavement %></td>
                </tr>
                <tr>
                  <th>Study leave:</th>
                  <td><%= @one_employee.leave.study_leave %></td>
                </tr>
                <tr>
                  <th>Time off:</th>
                  <td><%= @one_employee.leave.time_off %></td>
                </tr>
                <tr>
                  <th>Maternity:</th>
                  <td><%= @one_employee.leave.maternity %></td>
                </tr>
                <tr>
                  <th>Paternity:</th>
                  <td><%= @one_employee.leave.paternity %></td>
                </tr>
                <tr>
                  <th>Optional:</th>
                  <td><%= @one_employee.leave.optional %></td>
                </tr>
                <tr>
                  <th>Total leaves:</th>
                  <td><%= @total_leave %></td>
                </tr>


                </tbody>
              </table>
              <%= link_to 'Apply leave', apply_apply_leave_path, class:"btn btn-secondary"%>
            </div>
          </div>
        </div>

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Salary</h3>
            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <table class="table table-borderless table-hover">
                <tbody>
                <tr>
                  <th>Basic pay:</th>
                  <td><%= @one_employee.salary.basic_pay %> Rs</td>
                </tr>
                <tr>
                  <th>HRA:</th>
                  <td><%= @one_employee.salary.hra %> Rs</td>
                </tr>
                <tr>
                  <th>Statutory bonus:</th>
                  <td><%= @one_employee.salary.statutory_bonus %> Rs</td>
                </tr>
                <tr>
                  <th>Special allowance:</th>
                  <td><%= @one_employee.salary.special_allowance %> Rs</td>
                </tr>
                <tr>
                  <th>Total salary:</th>
                  <td><%= @total_salary %> Rs</td>
                </tr>



                </tbody>
              </table>

            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  </div>
  </div>
</section>

















<!--<h1>Welcome <%#= @one_employee.name %></h1>-->

<!--<h1>Basic Details</h1>  <%#= link_to 'Edit', edit_employee_registration_path%>-->
<!--<p><strong>Name: </strong> <%#= @one_employee.name %> </p>-->
<!--<p><strong>Date of Birth: </strong> <%#= @one_employee.dob %> </p>-->
<!--<p><strong>Phone_number: </strong> <%#= @one_employee.phone_number %> </p>-->
<!--<p><strong>Email: </strong> <%#= @one_employee.email %> </p>-->
<!--<p><strong>Gender: </strong> <%#= @one_employee.gender %> </p>-->
<!--<p><strong>Martial Status: </strong> <%#= @one_employee.martial_status %> </p>-->
<!--<p><strong>Blood Group: </strong> <%#= @one_employee.blood_group %> </p>-->
<!--<p><strong>Father's Name: </strong> <%#= @one_employee.fathers_name %> </p>-->
<!--<p><strong>Mother's Name: </strong> <%#= @one_employee.mothers_name %> </p>-->
<!--<p><strong>Address: </strong> <%#= @one_employee.address %> </p>-->

<!--<h1>Qualification</h1>   <%#= link_to 'Edit', edit_qualification_path(@one_employee.qualification.id) %>-->
<!--<p><strong>Designation: </strong> <%#= @one_employee.qualification.designation %> </p>-->
<!--<p><strong>Experience: </strong> <%#= @one_employee.qualification.experience %> </p>-->
<!--<p><strong>PG CGPA: </strong> <%#= @one_employee.qualification.pg_cgpa %> </p>-->
<!--<p><strong>PG year: </strong> <%#= @one_employee.qualification.pg_year %> </p>-->
<!--<p><strong>UG CGPA: </strong> <%#= @one_employee.qualification.ug_cgpa %> </p>-->
<!--<p><strong>UG year: </strong> <%#= @one_employee.qualification.ug_year %> </p>-->
<!--<p><strong>Diploma CGPA: </strong> <%#= @one_employee.qualification.diploma_cgpa %> </p>-->
<!--<p><strong>Diploma year: </strong> <%#= @one_employee.qualification.diploma_year %> </p>-->
<!--<p><strong>12th CGPA: </strong> <%#= @one_employee.qualification.twelve_th_percent %> </p>-->
<!--<p><strong>12th year: </strong> <%#= @one_employee.qualification.twelve_th_year %> </p>-->
<!--<p><strong>10th CGPA: </strong> <%#= @one_employee.qualification.ten_th_percent %> </p>-->
<!--<p><strong>10th year: </strong> <%#= @one_employee.qualification.ten_th_year %> </p>-->

<!--<h1>Remaining Leaves</h1>-->
<!--<p><strong>Sick: </strong> <%#= @one_employee.leave.sick %> </p>-->
<!--<p><strong>Privileged: </strong> <%#= @one_employee.leave.privileged %> </p>-->
<!--<p><strong>Breavement: </strong> <%#= @one_employee.leave.breavement %> </p>-->
<!--<p><strong>Study leave: </strong> <%#= @one_employee.leave.study_leave %> </p>-->
<!--<p><strong>Time off: </strong> <%#= @one_employee.leave.time_off %> </p>-->
<!--<p><strong>Maternity: </strong> <%#= @one_employee.leave.maternity %> </p>-->
<!--<p><strong>Paternity: </strong> <%#= @one_employee.leave.paternity %> </p>-->
<!--<p><strong>Optional: </strong> <%#= @one_employee.leave.optional %> </p>-->
<!--<p><strong>Total leaves: </strong> <%#= @total_leave %> </p>-->

<!--<h1>Salary details</h1>-->
<!--<p><strong>Basic pay: </strong> <%#= @one_employee.salary.basic_pay %> </p>-->
<!--<p><strong>HRA: </strong> <%#= @one_employee.salary.hra %> </p>-->
<!--<p><strong>Statutory bonus: </strong> <%#= @one_employee.salary.statutory_bonus %> </p>-->
<!--<p><strong>Special allowance: </strong> <%#= @one_employee.salary.special_allowance %> </p>-->
<!--<p><strong>Total salary: </strong> <%#= @total_salary %> </p>-->

app/views/home/_jumbotron.html.erb
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Welcome to EMS</h2>
              <p class="text-white-50 mb-5">Seamlessly manage all your employees!</p>

              <div class="form-outline form-white mb-4">
                <%= link_to 'Admin Login', new_admin_session_path, class:"btn btn-primary" %>
              </div>

              <div class="form-outline form-white mb-4">
                <%= link_to 'Employee Login', new_employee_session_path, class:"btn btn-primary "  %>
              </div>

            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<% unless admin_signed_in? or employee_signed_in? %>
  <%= render  'home/jumbotron'%>
<% end %>



<%# unless admin_signed_in? or employee_signed_in? %>
  <%#= link_to 'Admin Login', new_admin_session_path %>
  <%#= link_to 'Employee Login', new_employee_session_path %>
<%# end %>

<% if admin_signed_in? %>
  <%= render "employee" %>
<% end %>

<% if employee_signed_in? %>
  <%= render "employee_in" %>
<% end %>

app/views/home/show.html.erb
<section class="gradient-custom-blue">
  <br>
  <h2 class="fw-bold mb-2 text-uppercase text-md-center"><%= @employee.name %> details</h2>
  <div class="container py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-5">

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Basic Details</h3>
            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <table class="table table-borderless table-hover">
                <tbody>
                <tr>
                  <th>Name:</th>
                  <td><%= @employee.name %></td>
                </tr>
                <tr>
                  <th>Date of Birth:</th>
                  <td><%= @employee.dob %></td>
                </tr>
                <tr>
                  <th>Phone number:</th>
                  <td><%= @employee.phone_number %></td>
                </tr>
                <tr>
                  <th>Email:</th>
                  <td><%= @employee.email %></td>
                </tr>
                <tr>
                  <th>Gender:</th>
                  <td><%= @employee.gender %></td>
                </tr>
                <tr>
                  <th>Martial Status:</th>
                  <td><%= @employee.martial_status %></td>
                </tr>
                <tr>
                  <th>Blood Group:</th>
                  <td><%= @employee.blood_group %></td>
                </tr>
                <tr>
                  <th>Father's Name:</th>
                  <td><%= @employee.fathers_name %></td>
                </tr>
                <tr>
                  <th>Mother's Name:</th>
                  <td><%= @employee.mothers_name %></td>
                </tr>
                <tr>
                  <th>Address:</th>
                  <td><%= @employee.address %></td>
                </tr>

                </tbody>
              </table>
              <td> <%= link_to 'Edit', edit_home_path(@employee.id), class:"btn btn-secondary"%> </td>
            </div>
          </div>
        </div>

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Qualification</h3>
            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <table class="table table-borderless table-hover">
                <tbody>
                <tr>
                  <th>Designation:</th>
                  <td><%= @employee.qualification.designation %></td>
                </tr>
                <tr>
                  <th>Experience:</th>
                  <td><%= @employee.qualification.experience %></td>
                </tr>
                <tr>
                  <th>PG CGPA:</th>
                  <td><%= @employee.qualification.pg_cgpa %></td>
                </tr>
                <tr>
                  <th>PG year:</th>
                  <td><%= @employee.qualification.pg_year %></td>
                </tr>
                <tr>
                  <th>UG CGPA:</th>
                  <td><%= @employee.qualification.ug_cgpa %></td>
                </tr>
                <tr>
                  <th>UG year:</th>
                  <td><%= @employee.qualification.ug_year %></td>
                </tr>
                <tr>
                  <th>Diploma CGPA:</th>
                  <td><%= @employee.qualification.diploma_cgpa %></td>
                </tr>
                <tr>
                  <th>Diploma year:</th>
                  <td><%= @employee.qualification.diploma_year %></td>
                </tr>
                <tr>
                  <th>12th percentage:</th>
                  <td><%= @employee.qualification.twelve_th_percent %></td>
                </tr>
                <tr>
                  <th>12th year:</th>
                  <td><%= @employee.qualification.twelve_th_year %></td>
                </tr>
                <tr>
                  <th>10th percentage:</th>
                  <td><%= @employee.qualification.ten_th_percent %></td>
                </tr>
                <tr>
                  <th>10th year:</th>
                  <td><%= @employee.qualification.ten_th_year %></td>
                </tr>

                </tbody>
              </table>
              <%= link_to 'Edit', edit_qualification_path(@employee.qualification.id), class:"btn btn-secondary" %>
            </div>
          </div>
        </div>

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Remaining Leaves</h3>
            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <table class="table table-borderless table-hover">
                <tbody>
                <tr>
                  <th>Sick:</th>
                  <td><%= @employee.leave.sick %></td>
                </tr>
                <tr>
                  <th>Privileged:</th>
                  <td><%= @employee.leave.privileged %></td>
                </tr>
                <tr>
                  <th>Breavement:</th>
                  <td><%= @employee.leave.breavement %></td>
                </tr>
                <tr>
                  <th>Study leave:</th>
                  <td><%= @employee.leave.study_leave %></td>
                </tr>
                <tr>
                  <th>Time off:</th>
                  <td><%= @employee.leave.time_off %></td>
                </tr>
                <tr>
                  <th>Maternity:</th>
                  <td><%= @employee.leave.maternity %></td>
                </tr>
                <tr>
                  <th>Paternity:</th>
                  <td><%= @employee.leave.paternity %></td>
                </tr>
                <tr>
                  <th>Optional:</th>
                  <td><%= @employee.leave.optional %></td>
                </tr>
                <tr>
                  <th>Total leaves:</th>
                  <td><%= @total_leave %></td>
                </tr>


                </tbody>
              </table>
              <%= link_to 'Edit', edit_leafe_path(@employee.leave.id), type:"button", class:"btn btn-secondary" %>
            </div>
          </div>
        </div>

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Salary</h3>
            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <table class="table table-borderless table-hover">
                <tbody>
                <tr>
                  <th>Basic pay:</th>
                  <td><%= @employee.salary.basic_pay %> Rs</td>
                </tr>
                <tr>
                  <th>HRA:</th>
                  <td><%= @employee.salary.hra %> Rs</td>
                </tr>
                <tr>
                  <th>Statutory bonus:</th>
                  <td><%= @employee.salary.statutory_bonus %> Rs</td>
                </tr>
                <tr>
                  <th>Special allowance:</th>
                  <td><%= @employee.salary.special_allowance %> Rs</td>
                </tr>
                <tr>
                  <th>Total salary:</th>
                  <td><%= @total_salary %> Rs</td>
                </tr>

                </tbody>
              </table>
              <%= link_to 'Edit', edit_salary_path(@employee.salary.id), type:"button", class:"btn btn-secondary" %>
            </div>
          </div>
        </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>




<!--<h1><%#= @employee.name %> details </h1>-->

<!--<h1>Basic Details</h1>-->
<!--<p><strong>Name: </strong> <%#= @employee.name %> </p>-->
<!--<p><strong>Date of Birth: </strong> <%#= @employee.dob %> </p>-->
<!--<p><strong>Phone_number: </strong> <%#= @employee.phone_number %> </p>-->
<!--<p><strong>Email: </strong> <%#= @employee.email %> </p>-->
<!--<p><strong>Gender: </strong> <%#= @employee.gender %> </p>-->
<!--<p><strong>Martial Status: </strong> <%#= @employee.martial_status %> </p>-->
<!--<p><strong>Blood Group: </strong> <%#= @employee.blood_group %> </p>-->
<!--<p><strong>Father's Name: </strong> <%#= @employee.fathers_name %> </p>-->
<!--<p><strong>Mother's Name: </strong> <%#= @employee.mothers_name %> </p>-->
<!--<p><strong>Address: </strong> <%#= @employee.address %> </p>-->

<!--<h1>Qualification</h1>-->
<!--<p><strong>Designation: </strong> <%#= @employee.qualification.designation %> </p>-->
<!--<p><strong>Experience: </strong> <%#= @employee.qualification.experience %> </p>-->
<!--<p><strong>PG CGPA: </strong> <%#= @employee.qualification.pg_cgpa %> </p>-->
<!--<p><strong>PG year: </strong> <%#= @employee.qualification.pg_year %> </p>-->
<!--<p><strong>UG CGPA: </strong> <%#= @employee.qualification.ug_cgpa %> </p>-->
<!--<p><strong>UG year: </strong> <%#= @employee.qualification.ug_year %> </p>-->
<!--<p><strong>Diploma CGPA: </strong> <%#= @employee.qualification.diploma_cgpa %> </p>-->
<!--<p><strong>Diploma year: </strong> <%#= @employee.qualification.diploma_year %> </p>-->
<!--<p><strong>12th CGPA: </strong> <%#= @employee.qualification.twelve_th_percent %> </p>-->
<!--<p><strong>12th year: </strong> <%#= @employee.qualification.twelve_th_year %> </p>-->
<!--<p><strong>10th CGPA: </strong> <%#= @employee.qualification.ten_th_percent %> </p>-->
<!--<p><strong>10th year: </strong> <%#= @employee.qualification.ten_th_year %> </p>-->

<!--<h1>Remaining Leaves</h1>-->
<!--<p><strong>Sick: </strong> <%#= @employee.leave.sick %> </p>-->
<!--<p><strong>Privileged: </strong> <%#= @employee.leave.privileged %> </p>-->
<!--<p><strong>Breavement: </strong> <%#= @employee.leave.breavement %> </p>-->
<!--<p><strong>Study leave: </strong> <%#= @employee.leave.study_leave %> </p>-->
<!--<p><strong>Time off: </strong> <%#= @employee.leave.time_off %> </p>-->
<!--<p><strong>Maternity: </strong> <%#= @employee.leave.maternity %> </p>-->
<!--<p><strong>Paternity: </strong> <%#= @employee.leave.paternity %> </p>-->
<!--<p><strong>Optional: </strong> <%#= @employee.leave.optional %> </p>-->
<!--<p><strong>Total leaves: </strong> <%#= @total_leave %> </p>-->

<!--<h1>Salary details</h1>-->
<!--<p><strong>Basic pay: </strong> <%#= @employee.salary.basic_pay %> </p>-->
<!--<p><strong>HRA: </strong> <%#= @employee.salary.hra %> </p>-->
<!--<p><strong>Statutory bonus: </strong> <%#= @employee.salary.statutory_bonus %> </p>-->
<!--<p><strong>Special allowance: </strong> <%#= @employee.salary.special_allowance %> </p>-->
<!--<p><strong>Total salary: </strong> <%#= @total_salary %> </p>-->
<!--<br>-->