config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {
    # :sessions => "employee/sessions",
    :registrations => "employees/registrations"
  }

  devise_for :admins, :path => '', :path_names => {:sign_up => "s9442161" }

  root 'home#index'
  get 'home/about'

  resources :home, only: [:show, :edit, :update, :destroy]
  resources :qualifications, only: [:edit, :update]
  resources :leaves, only: [:edit, :update]
  resources :salaries, only: [:edit, :update]

  get 'apply/apply_leave'
  # put 'apply/:id', to: 'apply#update'
  put 'apply/update'

  get 'approve/dashboard'
  put 'approve/update'
  get 'status/leave_status'
  put 'status/update'
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :employee
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController

  def edit
    if admin_signed_in?
    @salary = Salary.find(params[:id])
  else
    redirect_to admin_session_path
  end
  end

  def update
    @salary = Salary.find(params[:id])
    if @salary.update(salary_params)
      flash[:notice] = "Employee details was updated successfully"
      if admin_signed_in?
        redirect_to home_path(@salary.employee.id)
      else
        redirect_to root_path
      end
    else
      render edit_salary_path
    end
  end

  private

  def salary_params
    params.require(:salary).permit( :basic_pay, :hra, :statutory_bonus, :special_allowance, :employee_id)
  end

end

app/views/salaries/edit.html.erb
<div class="container py-5 h-50 w-50">
  <div class="row d-flex justify-content-center align-items-center h-100">
    <div>
      <div class="card bg-dark text-white" style="border-radius: 1rem;">
        <div class="card-body p-5 text-center" >
          <h2 class="fw-bold mb-2 text-uppercase">Edit Salary</h2>
          <div class="mb-md-5 mt-md-4 pb-5">


            <%= form_with model: @salary do |f| %>

              <div class="form-outline form-white mb-4">
                <%= f.label :basic_pay %><br />
                <%= f.text_field :basic_pay, class:"form-label form-control form-control-lg"%>
              </div>

              <div class="form-outline form-white mb-4">
                <%= f.label :hra %><br />
                <%= f.text_field :hra, class:"form-label form-control form-control-lg"%>
              </div>

              <div class="form-outline form-white mb-4">
                <%= f.label :statutory_bonus %><br />
                <%= f.text_field :statutory_bonus, class:"form-label form-control form-control-lg"%>
              </div>

              <div class="form-outline form-white mb-4">
                <%= f.label :special_allowance %><br />
                <%= f.text_field :special_allowance, class:"form-label form-control form-control-lg"%>
              </div>

              <div class="actions">
                <%= f.submit "Update" , class:"btn btn-success" %>
              </div>
            <% end %>
            <br>
            <br>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>






















<!--<h1>Salary Details</h1>-->

<%#= form_with(scope: :qualifications,url: qualification_path(@qualifications), method: :put , local: true ) do |f| %>
<%#= form_with model: @salary do |f| %>

<!--  <div class="field">-->
<!--    <%#= f.label :basic_pay %><br />-->
    <%#= f.text_field :basic_pay, autofocus: true, autocomplete: "basic_pay" %>
<!--  </div>-->
<!--  <div class="field">-->
<!--    <%#= f.label :hra %><br />-->
    <%#= f.text_field :hra, autofocus: true, autocomplete: "hra" %>
<!--  </div>-->
<!--  <div class="field">-->
<!--    <%#= f.label :statutory_bonus %><br />-->
    <%#= f.text_field :statutory_bonus, autofocus: true, autocomplete: "statutory_bonus" %>
<!--  </div>-->
<!--  <div class="field">-->
<!--    <%#= f.label :special_allowance %><br />-->
    <%#= f.text_field :special_allowance, autofocus: true, autocomplete: "special_allowance" %>
<!--  </div>-->


  <%#= f.number_field :employee_id, value: @salary.employee.id, type: :hidden %>
  <%#= @qualification.employee.id %>

<!--  <div class="actions">-->
    <%#= f.submit %>
<!--  </div>-->

<%# end %>