config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {
    # :sessions => "employee/sessions",
    :registrations => "employees/registrations"
  }

  devise_for :admins, :path => '', :path_names => {:sign_up => "s9442161" }

  root 'home#index'
  get 'home/about'

  resources :home, only: [:show, :edit, :update, :destroy]
  resources :qualifications, only: [:edit, :update]
  resources :leaves, only: [:edit, :update]
  resources :salaries, only: [:edit, :update]

  get 'apply/apply_leave'
  # put 'apply/:id', to: 'apply#update'
  put 'apply/update'

  get 'approve/dashboard'
  put 'approve/update'
  get 'status/leave_status'
  put 'status/update'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%#= link_to 'EMS', root_path, class:"navbar-brand"%>
    <%= link_to href = root_path, class:"navbar-brand" do%>
    <%= image_tag "ems3.png", height: 35, class:"navbar-brand" %>
      <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item ">
          <!--          <a class="nav-link active" aria-current="page" href="#">Home</a>-->
          <% if employee_signed_in? %>
            <%= link_to 'Leave status', status_leave_status_path, class:"nav-link active" %>
          <% end  %>
        </li>
        <li class="nav-item ">
<!--          <a class="nav-link active" aria-current="page" href="#">Home</a>-->
          <% if employee_signed_in? %>
            <%= link_to 'Logout', destroy_employee_session_path, method: :delete, class:"nav-link active " %>
          <% end  %>
        </li>
<!--        <li class="nav-item ">-->
          <%# if admin_signed_in? %>
            <%#= link_to 'Edit profile', edit_admin_registration_path, class:"nav-link active"%>
          <%# end %>
<!--        </li>-->

        <% leave_count =  Leave.where(status: "Pending").count.to_s %>

        <li class="nav-item">
          <% if admin_signed_in? %>
            <%= link_to 'Leave Approval (' + leave_count +')', approve_dashboard_path, class:"nav-link active" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if admin_signed_in? %>
            <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class:"nav-link active" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>





<%#= link_to 'Home page', root_path %>

<%# if employee_signed_in? %>
  <%#= link_to 'Logout', destroy_employee_session_path, method: :delete %>
<%# end  %>

<%# if admin_signed_in? %>
  <%#= link_to 'Logout', destroy_admin_session_path, method: :delete %>
  <%#= link_to 'Edit profile', edit_admin_registration_path%>
<%# end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>EmsV1</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<section class="gradient-custom">
<%= render 'layouts/nav' %>

<% if notice %>
  <div class="alert alert-warning alert-dismissible fade show w-50 p-3 mx-auto" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show w-50 p-3 mx-auto" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<%= yield %>

</section>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>